services:
  - type: web
    name: n8n-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: America/Mexico_City
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_LOG_OUTPUT
        value: console
      - key: N8N_PAYLOAD_SIZE_MAX
        value: 16
      - key: N8N_METRICS
        value: true
    healthCheckPath: /healthz
    autoDeploy: true
